var perguntas = [
    "A Capoeira Regional é uma manifestação da cultura baiana, que foi criada em 1928 por Manoel dos Reis Machado. ele era conhecido como:",
    "O estilo da capoeira regional do Mestre Bimba teve a influência de dois estilos de luta: da Capoeira Angola e do Batuque (espécie de luta-livre comum na Bahia do século XIX) para criar este novo estilo.",
    "A capoeira regional apresenta algumas diferenças em relação a capoeira de angola. É característica da capoeira regional:",
    "Como se chama o golpe que visa acertar do abdômen para cima do adversário, cuja perna de trás da ginga é esticada para frente em linha reta visando empurrar ou deslocar o adversário?",
    "A rigor cada toque tem um significado e representa um estilo de jogo. Qual o significado do toque São Bento Grande?",
    "São instrumentos da capoeira:",
    "Mestre Bimba fundou o Centro de Cultura Física e Regional em que estado brasileiro?",
    "Como identificamos um jogo de capoeira regional?",
    "Como se chama o movimento básico da capoeira?",
    "A capoeira é uma herança cultural deixada pelos:"
];
var respostas = [
    ["Mestre Bimba",
    "Mestre Barrão",
    "Mestre Suassuna",
    "Mestre Pastinha",
    "Mestre Jogo de dentro"],
    ["Boxe e maculelê",
    "Boxe e batuque",
    "Capoeira de angola e o boxe",
    "Capoeira de angola e o batuque",
    "Capoeira de angola e o maculelê"],
    ["Ela na sua música não resgata a herança cultural dos escravos.",
    "É uma atividade aberta a todos basta chegar e praticar sem a necessidade de uniformes ou faixas.",
    "É uma capoeira menos rígida e mais livre com os mesmos elementos (golpes) da capoeira de angola.",
    "Não utiliza o uso de instrumentos como o berimbau ou pandeiro, somente palmas.",
    "Para fugir de qualquer pista que lembrasse a origem marginalizada da capoeira, eliminou a malícia da postura do capoeirista, colocando-o em pé."],
    ["Au",
    "Bênção",
    "Cocorinha",
    "Chapa de costas",
    "Meia lua de frente"],
    ["É um toque de apresentação.",
    'É um toque de apresentação.É um toque que tem ritmo agressivo,um "jogo duro".',
    "É o toque de aviso, chama a atenção dos capoeiristas que chegou estranhos na roda.",
    "È um toque especial para os alunos formados por Mestre Bimba.",
    "É um toque que chama para um jogo compassado, curtido, malicioso e floreado."],
    ["Atabaque, pandeiro e castanholas.",
    "Atabaque, cuíca, pandeiro e caxixi.",
    "Berimbau, atabaque, agogô, pandeiro e flauta.",
    "Berimbau, atabaque, agogô, pandeiro e caxixi.",
    "Berimbau, atabaque, agogô, pandeiro e violão."],
    ["","","","",""],
    ["","","","",""],
    ["","","","",""],
    ["","","","",""]
];